name : Test
brand : My Project
description : This is the description of my project
keyword : 
url : http://jlarfors.github.io/
email : jacob@larfors.com
github: [metadata]
markdown : kramdown
exclude :
  - node_modules
