name : Test
brand : My Project
description : This is the description of my project
keyword : 
url : http://jlarfors.github.io/
repository : https://github.com/jlarfors/jekyll-test
email : jacob@larfors.com
github: [metadata]
markdown : kramdown
exclude :
  - node_modules
